const data={
    products : [
        {
        _id : '1',
        name: 'QUAKER Rolled Oats Pouch',
        weight :'500gm',
        category:'Grains',
        image:'https://esobdeal.com/wp-content/uploads/2020/09/Cowhead-Organic-Rolled-Oats.jpg',
        brand:'QUAKER',
        price:0,
        countInStock:40,
        rating:4,
        numReviews:10,
        description:'Oats are rich in carbs and fiber, but also higher in protein and fat than most other grains.Nutritional value per 100 g (3.5 oz) <br><br> Carbohydrates:	67.70 g <br><br>  Sugars	0.99 g <br><br> Dietary fiber	10.1 g <br><br> Fat	6.52 g',
        Neutri_images:'',

    },
    {
        _id : '2',
        name: 'White Quinoa',
        weight :'500gm',
        category:'Grains',
        image:'https://assetscdn1.paytm.com/images/catalog/product/F/FA/FASCHEF-URBANO-CHEF632071A0B3DE54/1561500755560_8.jpg?imwidth=320&impolicy=hq',
        brand:'QChef Urbano',
        rating:4.5,
        price:0,
        countInStock:40,
        numReviews:17,
        description:'Cooked quinoa consists of 71.6% water, 21.3% carbohydrates, 4.4% protein, and 1.92% fat. One cup (185 grams) of cooked quinoa contains 222 calories.',
        Neutri_images:'',
    },
    {
        _id : '3',
        name: 'Multi-Grain Flour',
        weight :'500gm',
        category:'Grains',
        image: 'https://cdn.shopify.com/s/files/1/1610/6897/products/oie_16225712K0SzvVbn.jpg?v=1560867239',
        brand:'Deep Atta',
        rating:4,
        price:0,
        countInStock:40,
        numReviews:19,
        description:'Energy	104 cal	5%.Multigrain roti is made with 5 nutritious flours that provide iron, protein, fiber and vitamin b.<br><br> Value per per roti      % Daily Values <br><br> Protein	2.7 g	5% <br><br> Carbohydrates	16.2 g	5% <br><br> Fiber	2.8 g	11%',
        Neutri_images:'',
    },
    {
        _id : '4',
        name: 'Whole Wheat Fusilli Pasta',
        weight :'500gm',
        category:'Grains',
        image:'https://dailybazar.com.bd/wp-content/uploads/2020/07/Reggia-Whole-Wheat-Fusili-Pasta-Organic-500gm.jpg',
        brand:'Reggia',
        rating:4.5,
        price:0,
        countInStock:40,
        numReviews:19,
        description:'Whole-grain pasta is typically high in fiber, manganese, selenium, copper and phosphorus.<br><br> Per 100 grams <br><br> Energy (kJ/Kcal): 1604kJ/380kcal.<br><br> Fat (g): 1.70.<br><br> Fatty acids (g): 0.30.<br><br> Carbohydrates (g): 75.00.<br><br> Of which sugars (g): 4.00.<br><br> Proteins (g): 12.00.<br><br> Salt (g): 0.00.',
        Neutri_images:'',
    },
    {
        _id : '5',
        name: 'Brown Rice',
        weight :'500gm',
        category:'Grains',
        image:'https://images-na.ssl-images-amazon.com/images/I/61hQBrervrL._AC_SL1000_.jpg',
        brand:'Kohinoor Charminar',
        rating:4,
        price:0,
        countInStock:40,
        numReviews:10,
        description:'Brown rice is a highly nutritious food. It is a whole grain that is relatively low in calories (216 calories per cup), high in fiber, gluten-free and can be incorporated into a variety of dishes.<br><br> Nutrition information <br><br>  366 Calories.<br><br> 1.6g Total Fat.<br><br> 0g Saturated Fat.<br><br> 0.55g Trans Fat.<br><br> 78g Carbohydrates.<br><br> 0g Sugar.<br><br> 9g Protein.',
        Neutri_images:'',
    },
    {
        _id : '6',
        name: 'Chia Seeds',
        weight :'500gm',
        category:'Grains',
        image:'https://cdn.shopify.com/s/files/1/0273/3840/7959/products/500_050a93a8-7f60-46aa-bffa-4e2213d3ebd8_1024x1024.jpg?v=1616152103',
        brand:'Bold Pack',
        rating:4.8,
        price:0,
        countInStock:40,
        numReviews:10,
        description:'Two tablespoons of chia seeds have almost 10 grams of fiber. That is around 40 percent of the recommended daily intake. Diets high in fiber have been linked to weight loss. According to 2015 research , eating 30 grams of fiber daily may help you lose as much weight as if you followed a more complicated diet.',
        Neutri_images:'',
    },
    
],
};
export default data;